"""Edit profile class

Revision ID: 3aaef26ff4fd
Revises: 808b3806eeb3
Create Date: 2024-03-24 01:45:56.714389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aaef26ff4fd'
down_revision = '808b3806eeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
