"""subtasks

Revision ID: 74deef164afd
Revises: 3aaef26ff4fd
Create Date: 2024-04-08 00:51:59.065060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74deef164afd'
down_revision = '3aaef26ff4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('parent_task_description', sa.String(length=120), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtasks')
    # ### end Alembic commands ###
